#!/usr/bin/env python3
"""Emit app/src/data/markets.ts from the frozen settled snapshot.

The snapshot holds the exact display strings the live page painted, so the replica
renders them verbatim instead of re-formatting numbers and risking a mismatch.
See docs/SCOPE.md for the formatting contract and why it is frozen.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SNAP = ROOT / 'reference' / 'settled' / 'markets_snapshot.json'
OUT = ROOT / 'app' / 'src' / 'data' / 'markets.ts'

HEADER = '''/**
 * Frozen market snapshot.
 *
 * GENERATED by tools/gen_markets.py from reference/settled/markets_snapshot.json.
 * Do not edit by hand.
 *
 * `price` / `change` / `volume` / `leverage` are the exact display strings the
 * live page painted, so the replica's settled panel is comparable to the capture
 * character-for-character. Numbers are frozen data -- see docs/SCOPE.md.
 */
export type Market = {
  symbol: string;
  name: string;
  address: string;
  marketType: string;
  maxLeverage: number;
  price: string;
  change: string;
  changeDir: 'desk-up' | 'desk-down';
  volume: string;
  leverage: string;
};

'''


def main():
    snap = json.loads(SNAP.read_text())
    rows = []
    for m in snap['markets']:
        c = m['captured']
        rows.append({
            'symbol': m['symbol'],
            'name': m['name'],
            'address': m['address'],
            'marketType': m['marketType'],
            'maxLeverage': m['maxLeverage'],
            'price': c['price'],
            'change': c['change'],
            'changeDir': c['changeDir'],
            'volume': c['volume'],
            'leverage': c['leverage'],
        })
    lines = [HEADER]
    lines.append('export const MARKETS: Market[] = [')
    for r in rows:
        lines.append('  { ' + ', '.join(
            '%s: %s' % (k, json.dumps(v)) for k, v in r.items()) + ' },')
    lines.append('];')
    lines.append('')
    lines.append('export const ETH_PRICE = %s;' % json.dumps(snap.get('ethPrice')))
    lines.append('')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(lines))
    print('wrote %s: %d markets, ethPrice=%s' % (OUT, len(rows), snap.get('ethPrice')))
    for r in rows[:3]:
        print('  ', r['symbol'], r['price'], r['change'], r['volume'], r['leverage'],
              r['changeDir'])


if __name__ == '__main__':
    main()
